### ISSUE TITLE
Высокая избыточность скриптов

### ISSUE THREAD

**Issue by T-Maxxx** [volkv/CoD4Sniper#1]
@volkv Тот, кто передал их тебе - просто извлёк все скрипты из common_mp.ff. По факту, используются только несколько скриптов. Точно - _globallogic, _dev, может, еще какие-то. Давно это было.

**Comment by volkv** [comment]
Да, спасибо, что почистил.
Вроде бы, осталось то, что нужно. Только с _helicopter не очень понятно - все бонусы же выпилены в _hardpoints?

**Comment by T-Maxxx** [comment]
Не уверен. Я туда мог поместить какой-то код в связи с нехваткой места.
