### ISSUE TITLE
Переполнение Hudelems

### ISSUE THREAD

**Issue by volkv** [volkv/CoD4Sniper#3]
Если много игроков на сервере, то ошибка вылезает. Более 1024 Худов. 
Вроде бы, должны чиститься тут - [https://github.com/volkv/CoD4Sniper/blob/master/maps/mp/gametypes/_rank.gsc#L314-L315](url)
```
^1******* script runtime error *******
GScr_NewHudElem: Exceeded limit of Hudelems: (file 'maps/mp/gametypes/_hud_util.gsc', line 235)
 fontElem = newClientHudElem( self );
            *
^1called from:
(file 'maps/mp/gametypes/_dev.gsc', line 12)
 data.underLine = createFontString( "default", 1.4 );
                  *
^1called from:
(file 'maps/mp/gametypes/_rank.gsc', line 331)
  self.hud_rankscroreupdate = maps\mp\gametypes\_dev::newScoreUpdate();
                              *
^1called from:
(file 'maps/mp/gametypes/_rank.gsc', line 341)
  self initScoreHud( false );
       *
^1started from:
(file 'maps/mp/gametypes/_rank.gsc', line 339)
  self waittill("spawned_player");
       *
^1************************************
----- Server Shutdown -----
```

**Comment by T-Maxxx** [comment]
@volkv Пишешь моё имя после собачки и я получаю оповещение. Да, мой косяк, в `file 'maps/mp/gametypes/_dev.gsc', line 12)`. Сейчас исправлю.

**Comment by volkv** [comment]
Ок, буду знать
Спасибо

**Comment by volkv** [comment]
P.S. это получается при удалении **self.hud_rankscroreupdate** дочерняя **self.hud_rankscroreupdate.underLine** остается ?

**Comment by T-Maxxx** [comment]
Да. А ты думал, что удаляются все дочерние поля в зависимости от их типа? Нет, это типичная утечка памяти.
