### ISSUE TITLE
script runtime error

### ISSUE THREAD

**Issue by 3aTeuHuk** [volkv/CoD4Sniper#5]
^1******* script runtime error *******
pair 'undefined' and '0.25' has unmatching types 'undefined' and 'float': (file 'maps/mp/gametypes/_dev.gsc', line 444)
 if( self.borderPunish - 0.25 == level.bordersPunishmentTime ){
                       *
^1started from:
(file 'maps/mp/gametypes/_dev.gsc', line 442)
 wait level.bordersPunishmentTime;
 *
^1************************************
----- Server Shutdown -----

**Comment by 3aTeuHuk** [comment]
^1******* script runtime error *******
pair '' and 'undefined' has unmatching types 'string' and 'undefined': (file 'maps/mp/gametypes/_globallogic.gsc', line 4316)
  if ( isDefined( level.players[entry].killedPlayers[""+self.clientid] ) )
                                                       *
^1called from:
(file 'maps/mp/gametypes/_callbacksetup.gsc', line 49)
 [[level.callbackPlayerDisconnect]]();
         *
^1started from:
(file 'maps/mp/gametypes/_callbacksetup.gsc', line 46)
CodeCallback_PlayerDisconnect()
*
^1************************************
----- Server Shutdown -----

**Comment by T-Maxxx** [comment]
@3aTeuHuk Если написать мой ник после собачки, я получу оповещение. Это удобно, можно никого не просить написать мне.
Первую ошибку исправил, вторая, не моя. Возможно, появляется из-за другой ошибки. Трудно сказать. По крайней мере, исходные коды оригинальной игры хорошо отлажены.

**Comment by 3aTeuHuk** [comment]
@T-Maxxx учту. Спасибо.
