### ISSUE TITLE
Комментарии к коду.

### ISSUE THREAD

**Issue by 3aTeuHuk** [volkv/CoD4Sniper#7]
@T-Maxxx привет. Возможно написать комментарии к коду отвечающему за границы?
Пробовал по примеру "мокрого дела" провести прямую на "блоке" в _dev.gsc. Получилось, выводится предупреждение. Далее в war.gsc добавляю карту в switch(level.script) и при загрузке карты ошибка. Где еще нужно вносить изменения ?
`Sys_Error: script runtime error
(see console for details)
 wait 0.05;`

**Comment by T-Maxxx** [comment]
@3aTeuHuk Лучше вообще не трогать ту магию, что там происходит. Но если вкратце, то граница строится по точкам. Каждые 2 точки объединяются в прямые. Если ты пересекаешь хотя бы одну прямую, считается, что ты за границей. В основе лежит теоремка о взаимном расположении 2-х точек относительно прямой (или нет, не помню уже, какая это версия). Там захардкожены координаты этих самых точек и присутствует миллион сравнений больше\меньше. Если получится подогнать значения - будет работать. Если нет - увы.

Сейчас у меня есть система границ, корректно работающая на трапециях, но нет конфигов для границ. Сессия закончится - попробую написать BSP компилятор и напишу систему для произвольного многоугольника, чтобы не мудохаться с этими координатами  (начал, но что-то так себе пока).

**Comment by volkv** [comment]
по 1ой линии проводить - не сложно.
летишь в начало линии - /viewpos, получаешь X1, Y1, летишь в конец X2,Y2 
потом в tempy заносишь и по примеру остальных карт.
2 линии, для одной и другой команды

tempy = _calcLine(X1,X2,Y1,Y2 x);

вот для блока

```
blocborder(team)
{
	self endon("disconnect");
	self endon("death");
	self endon("joined_spectators");
	for(;;wait .25)
	{
		if( level.inGracePeriod )
			level waittill( "grace_period_ending" );
		x = self.origin[0];
		y = self.origin[1];
		if(team == "allies")
		{
			tempy = _calcLine(4760, -1314, -6465, -6281, x);
			// iprintln(self.origin[0] + "___" + self.origin[1] + "____" + tempy);
				if(y>=tempy){
					
				self.borderPunish += 0.25;
				self thread borderPunishment();
			}
		}
		else if (team == "axis")
		{
			tempy = _calcLine(3504, -3004, -5309, -5420, x);
			//			iprintln(self.origin[0] + "___" + self.origin[1] + "____" + tempy);
				if(y<=tempy){
				self.borderPunish += 0.25;
				self thread borderPunishment();
			}
		}
	}
}
```

**Comment by 3aTeuHuk** [comment]
@T-Maxxx как работают 2 точки с прямыми я приблизительно понял. Методом проб и ошибок можно разобраться. Мне больше интересна та часть где тебя перебрасывает на респаун если границу пересечь. 
@volkv спасибо. Тут я прямую проводил как на Мокром деле.
`blocborder(team)
{
	self endon("disconnect");
	self endon("death");
	self endon("joined_spectators");
	for(;;wait 0.25)
	{
		if( level.inGracePeriod )
			level waittill( "grace_period_ending" );
		y = self.origin[1];
		if(team == "allies")
		{
			if(y>-5985){
				self.borderPunish += 0.25;
				self thread borderPunishment();
			}
		}
		else if (team == "axis")
		{
			if(y<-5708){
				self.borderPunish += 0.25;
				self thread borderPunishment();
			}
		}
	}
}`
Но как быть здесь(war.gsc):
`game["dialog"]["gametype"] = "team_deathmtch";
	wait 0.05;
	level.useExtraSpawn = false;
	if( level.extraSpawns )
		switch(level.script)
		{
			case "mp_convoy":
			case "mp_cargoship":
			case "mp_pipeline":
			case "mp_backlot":
			case "mp_strike":
			case "mp_countdown":
			case "mp_bog":
			case "mp_crossfire":
			case "mp_overgrown":
			**case "mp_bloc":**
				level.useExtraSpawn = true;
				maps\mp\gametypes\_dev::extraSpawnPoints();
				break;
		}`

**Comment by 3aTeuHuk** [comment]
Каюсь. Осознал. Мой косяк! Указал координату респауна с ошибкой! Все работает )
