### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by 3aTeuHuk** [volkv/CoD4Sniper#8]
@T-Maxxx привет.
^1******* script runtime error *******
cannot cast undefined to string: (file 'maps/mp/gametypes/_class.gsc', line 646)
 if( isSubstr( class, "CLASS_CUSTOM" ) )
               *
^1called from:
(file 'maps/mp/gametypes/_dev.gsc', line 686)
  self maps\mp\gametypes\_class::giveLoadout( self.team, self.class );
       *
^1called from:
(file 'maps/mp/gametypes/_menus.gsc', line 104)
    self maps\mp\gametypes\_dev::extraSpectator( false );
         *
^1started from:
(file 'maps/mp/gametypes/_dev.gsc', line 684)
  wait 0.05;
  *
^1************************************

**Comment by T-Maxxx** [comment]
@3aTeuHuk Может, для разнообразия, будете использовать скрипты из этого репозитория?

**Comment by 3aTeuHuk** [comment]
@T-Maxxx то есть ?

**Comment by T-Maxxx** [comment]
@3aTeuHuk Я не вижу [тут](https://github.com/volkv/CoD4Sniper/blob/master/maps/mp/gametypes/_dev.gsc#L646) 686-ю строчку.

**Comment by 3aTeuHuk** [comment]
@T-Maxxx в репозитории строка [498](https://github.com/volkv/CoD4Sniper/blob/master/maps/mp/gametypes/_dev.gsc#L498). Мной добавлены только границы на другие карты в остальной код я не вмешивался.

**Comment by T-Maxxx** [comment]
@3aTeuHuk Я тебе больше скажу, там 4 вхождения этой функции в скриптах, 3 из которых это вызовы и 2 подходят под описание. Но проблема в том, что ты присылаешь лог с сервера, на котором используются не эти скрипты, а в этих этой проблемы может и не быть.

**Comment by 3aTeuHuk** [comment]
@T-Maxxx ясно. Вопросов больше нет.
